PATHS:
  RAW_COVID_DATA: 'D:/Documents/Work/covid-cxr/data/covid-chestxray-dataset-master/'
  RAW_OTHER_DATA: 'D:/Documents/Work/covid-cxr/data/other/'
  PROCESSED_DATA: 'data/processed/'

DATA:
  IMG_DIM: [224, 224]
  VAL_SPLIT: 0.05
  TEST_SPLIT: 0.1

NN:
  RESNET:
    NODES:
      DENSE0: 128
    LR: 0.001
    DROPOUT: 0.3

TRAIN:
  EPOCHS: 100
