PATHS:
  RAW_COVID_DATA: 'D:/Documents/Work/covid-cxr/data/covid-chestxray-dataset/'
  RAW_OTHER_DATA: 'D:/Documents/Work/covid-cxr/data/other/'
  PROCESSED_DATA: 'data/processed/'
  TRAIN_IMGS: 'data/processed/train/'
  VAL_IMGS: 'data/processed/val/'
  TEST_IMGS: 'data/processed/test/'
  TRAIN_SET: 'data/processed/train_set.csv'
  VAL_SET: 'data/processed/val_set.csv'
  TEST_SET: 'data/processed/test_set.csv'
  IMAGES: 'documents/generated_images/'
  LOGS: 'results\\logs\\'
  MODEL_WEIGHTS: 'results/models/model.h5'
  MODEL_TO_LOAD: 'results/models/model.h5'
  LIME_EXPLAINER: './data/interpretability/lime_explainer.pkl'

DATA:
  IMG_DIM: [224, 224]
  VAL_SPLIT: 0.05
  TEST_SPLIT: 0.1
  KAGGLE_DATA_FRAC: 0.2

NN:
  MOBILENET:
    NODES:
      DENSE0: 512
    LR: 0.01
    DROPOUT: 0.25
  DCNN1:
    KERNEL_SIZE: (3,3)
    STRIDES: (1,1)
    INIT_FILTERS: 32
    FILTER_EXP: 2
    NODES:
      DENSE0: 128
      DENSE1: 32
    LR: 0.00001
    DROPOUT: 0.25
    L2_LAMBDA: 0.0001

TRAIN:
  EXPERIMENT_TYPE: 'single_train'
  BATCH_SIZE: 16
  EPOCHS: 60
  THRESHOLDS: 0.5   # Can be changed to list of values in range [0, 1]
  PATIENCE: 5
  IMB_STRATEGY: 'class_weight'  # One of {'class_weight', 'random_oversample'}
  POS_WEIGHT: 0.5

LIME:
  NUM_SAMPLES: 1000
  NUM_FEATURES: 20000
  KERNEL_WIDTH: 1.25
  FEATURE_SELECTION: 'lasso_path'

PREDICTION:
  THRESHOLD: 0.5