PATHS:
  RAW_COVID_DATA: 'D:/Documents/Work/covid-cxr/data/covid-chestxray-dataset/'   # Path of extracted COVID dataset https://github.com/ieee8023/covid-chestxray-dataset
  RAW_OTHER_DATA: 'D:/Documents/Work/covid-cxr/data/rsna/'                       # Path of extracted NIH dataset https://nihcc.app.box.com/v/ChestXray-NIHCC
  PROCESSED_DATA: 'data/processed/'
  TRAIN_IMGS: 'data/processed/train/'
  VAL_IMGS: 'data/processed/val/'
  TEST_IMGS: 'data/processed/test/'
  TRAIN_SET: 'data/processed/train_set.csv'
  VAL_SET: 'data/processed/val_set.csv'
  TEST_SET: 'data/processed/test_set.csv'
  IMAGES: 'documents/generated_images/'
  LOGS: 'results\\logs\\'
  MODEL_WEIGHTS: 'results/models/model.h5'
  MODEL_TO_LOAD: 'results/models/model.h5'
  LIME_EXPLAINER: './data/interpretability/lime_explainer.pkl'

DATA:
  IMG_DIM: [224, 224]
  VAL_SPLIT: 0.08
  TEST_SPLIT: 0.1
  KAGGLE_DATA_FRAC: 0.2
  NUM_RSNA_IMGS: 907
  #CLASSES: ['non-COVID-19', 'COVID-19']                # Classes for binary classification
  CLASSES: ['normal', 'COVID-19', 'other_pneumonia']    # Classes for multiclass classification (3 classes)

TRAIN:
  EXPERIMENT_TYPE: 'single_train'
  BATCH_SIZE: 16
  EPOCHS: 150
  THRESHOLDS: 0.5   # Can be changed to list of values in range [0, 1]
  PATIENCE: 7
  IMB_STRATEGY: 'class_weight'          # One of {'class_weight', 'random_oversample'}
  CLASS_MODE: 'multiclass'              # One of {'binary', 'multiclass'}
  #CLASS_MULTIPLIER: [0.15, 1.0]                   # Class multiplier for binary classification
  CLASS_MULTIPLIER: [0.9, 1.0, 0.9]            # Class multiplier for multiclass classification (3 classes)

NN:
  DCNN_BINARY:
    KERNEL_SIZE: (3,3)
    STRIDES: (1,1)
    INIT_FILTERS: 16
    FILTER_EXP_BASE: 3
    MAXPOOL_SIZE: (2,2)
    CONV_BLOCKS: 3
    NODES_DENSE0: 128
    LR: 0.0003
    DROPOUT: 0.40
    L2_LAMBDA: 0.0001
  DCNN_MULTICLASS:
    KERNEL_SIZE: (3,3)
    STRIDES: (1,1)
    INIT_FILTERS: 16
    FILTER_EXP_BASE: 3
    MAXPOOL_SIZE: (2,2)
    CONV_BLOCKS: 3
    NODES_DENSE0: 128
    LR: 0.0003
    DROPOUT: 0.40
    L2_LAMBDA: 0.0001

LIME:
  KERNEL_WIDTH: 1.75
  FEATURE_SELECTION: 'lasso_path'
  NUM_FEATURES: 10000
  NUM_SAMPLES: 4000
  COVID_ONLY: false

PREDICTION:
  THRESHOLD: 0.5