PATHS:
  RAW_COVID_DATA: 'D:/Documents/Work/covid-cxr/data/covid-chestxray-dataset/'   # Path of extracted COVID dataset https://github.com/ieee8023/covid-chestxray-dataset
  RAW_OTHER_DATA: 'D:/Documents/Work/covid-cxr/data/other/'                     # Path of extracted other dataset https://www.kaggle.com/paultimothymooney/chest-xray-pneumonia
  PROCESSED_DATA: 'data/processed/'
  TRAIN_IMGS: 'data/processed/train/'
  VAL_IMGS: 'data/processed/val/'
  TEST_IMGS: 'data/processed/test/'
  TRAIN_SET: 'data/processed/train_set.csv'
  VAL_SET: 'data/processed/val_set.csv'
  TEST_SET: 'data/processed/test_set.csv'
  IMAGES: 'documents/generated_images/'
  LOGS: 'results\\logs\\'
  MODEL_WEIGHTS: 'results/models/model.h5'
  MODEL_TO_LOAD: 'results/models/model.h5'
  LIME_EXPLAINER: './data/interpretability/lime_explainer.pkl'

DATA:
  IMG_DIM: [224, 224]
  VAL_SPLIT: 0.05
  TEST_SPLIT: 0.1
  KAGGLE_DATA_FRAC: 0.2
  CLASSES: ['COVID-19', 'viral_pneumonia', 'bacterial_pneumonia', 'normal']

TRAIN:
  EXPERIMENT_TYPE: 'single_train'
  BATCH_SIZE: 16
  EPOCHS: 60
  THRESHOLDS: 0.5   # Can be changed to list of values in range [0, 1]
  PATIENCE: 5
  IMB_STRATEGY: 'class_weight'  # One of {'class_weight', 'random_oversample'}
  POS_WEIGHT: 0.5
  CLASS_MODE: 'multiclass'

NN:
  DCNN_BINARY:
    KERNEL_SIZE: (3,3)
    STRIDES: (1,1)
    INIT_FILTERS: 32
    FILTER_EXP_BASE: 2
    MAXPOOL_SIZE: (2,2)
    CONV_BLOCKS: 4
    NODES_DENSE0: 128
    LR: 0.00001
    DROPOUT: 0.25
    L2_LAMBDA: 0.0001
  DCNN_MULTICLASS:
    KERNEL_SIZE: (3,3)
    STRIDES: (1,1)
    INIT_FILTERS: 32
    FILTER_EXP_BASE: 2
    MAXPOOL_SIZE: (2,2)
    CONV_BLOCKS: 4
    NODES_DENSE0: 128
    LR: 0.00001
    DROPOUT: 0.25
    L2_LAMBDA: 0.0001

LIME:
  KERNEL_WIDTH: 1.75
  FEATURE_SELECTION: 'lasso_path'
  NUM_FEATURES: 10000
  NUM_SAMPLES: 4000

PREDICTION:
  THRESHOLD: 0.5